/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import Conexion_BD.Conexion;
import Controladores.Ctrl_Clientes;
import Controladores.Reportes_pdf;
import static Graficas.Abonos_vista.ciudadSeleccionada;
import static Graficas.Abonos_vista.guardarOrden;
import Modelos.Clientes;
import java.awt.Color;
import java.awt.HeadlessException;
import static java.awt.SystemColor.control;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Ramon
 */
public class Clientes_vista extends javax.swing.JPanel {

    PazYSalvo Paz = new PazYSalvo();

    int obtenerIdCategoriaCombo = 0;
    String ciudad;

    int a;
    String valor = "";
    private Singlenton singleton = Singlenton.obtenerInstancia();
    boolean probar = false;

    public Clientes_vista() {
        initComponents();
        restringirSoloNumeros(txtapellido);
        restringirSoloNumeros(txtprestamo);
        restringirSoloNumeros(txtprestamo);
        restringirSoloNumeros(txtprestamo_interes);
        restringirSoloNumeros(txtplazo_dias);
        restringirSoloNumeros(txtvalor_cuota);

        model = (DefaultTableModel) tabla_clientes.getModel();
        this.comprobar();
        id_eliminar.setEnabled(false);
        this.cargarCiudadbox(combo_categoria);
        txtnombre.requestFocus(true);

    }
    DefaultTableModel model;
    Connection connect;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        q = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        agregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new ColorMora();
        eliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combo_categoria = new javax.swing.JComboBox<>();
        txtvalor_cuota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtplazo_dias = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtprestamo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        id_eliminar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        txtprestamo_interes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        agregar1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_clientes1 = new ColorMora();
        eliminar1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        combo_categoria1 = new javax.swing.JComboBox<>();
        txtvalor_cuota1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtplazo_dias1 = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        txtnombre1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtprestamo1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        editar1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        id_eliminar1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtdir1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtcelular1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        txtprestamo_interes1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout qLayout = new javax.swing.GroupLayout(q);
        q.setLayout(qLayout);
        qLayout.setHorizontalGroup(
            qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        qLayout.setVerticalGroup(
            qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setBackground(new java.awt.Color(102, 255, 102));
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarMouseEntered(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AGREGAR");

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar);
        agregar.setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 100, 26));

        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Fecha", "Prestamo", "P.interes", "Valor", "Mora", "Direccion", "Numero", "cuotas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_clientesMouseClicked(evt);
            }
        });
        tabla_clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_clientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_clientes);
        if (tabla_clientes.getColumnModel().getColumnCount() > 0) {
            tabla_clientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabla_clientes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabla_clientes.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabla_clientes.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabla_clientes.getColumnModel().getColumn(5).setPreferredWidth(45);
            tabla_clientes.getColumnModel().getColumn(6).setPreferredWidth(40);
            tabla_clientes.getColumnModel().getColumn(7).setPreferredWidth(80);
            tabla_clientes.getColumnModel().getColumn(9).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1030, 430));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ELIMINAR");

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar);
        eliminar.setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, 26));

        combo_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_categoriaItemStateChanged(evt);
            }
        });
        combo_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_categoriaActionPerformed(evt);
            }
        });
        jPanel1.add(combo_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, -1));

        txtvalor_cuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalor_cuotaActionPerformed(evt);
            }
        });
        txtvalor_cuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvalor_cuotaKeyPressed(evt);
            }
        });
        jPanel1.add(txtvalor_cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 70, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-nombre-30.png"))); // NOI18N
        jLabel1.setText("CELULAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        txtplazo_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplazo_diasActionPerformed(evt);
            }
        });
        txtplazo_dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtplazo_diasKeyPressed(evt);
            }
        });
        jPanel1.add(txtplazo_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 120, -1));

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoKeyPressed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-ciudad-35.png"))); // NOI18N
        jLabel7.setText("DIRECCION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-usuario-30.png"))); // NOI18N
        jLabel10.setText("NOMBRE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 30));

        txtprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprestamoActionPerformed(evt);
            }
        });
        txtprestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprestamoKeyPressed(evt);
            }
        });
        jPanel1.add(txtprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-dinero-30.png"))); // NOI18N
        jLabel9.setText("P.INTERES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-tiempo-de-dinero-30.png"))); // NOI18N
        jLabel11.setText("CUOTAS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLIENTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CIUDAD:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 52, 30));

        editar.setText("Editar");
        editar.setBorder(null);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 30));

        jButton2.setText("NoEditar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CLAVOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 30));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-porcentaje-30.png"))); // NOI18N
        jLabel14.setText("Valor");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 102));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PAZ Y SALVO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));
        jPanel1.add(id_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 120, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 20, 30));

        txtdir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdirKeyPressed(evt);
            }
        });
        jPanel1.add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-nombre-30.png"))); // NOI18N
        jLabel8.setText("FECHA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        txtcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelularActionPerformed(evt);
            }
        });
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcelularKeyPressed(evt);
            }
        });
        jPanel1.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, -1));

        jButton3.setText("CARTONES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 150, 50));

        jButton4.setText("CARTON ESTE CLIENTE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 240, -1));

        txt.setText("jTextField1");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 870, -1, -1));

        txt2.setText("jTextField1");
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 880, -1, -1));

        txt3.setText("jTextField1");
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 870, -1, -1));

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 960, -1, 10));

        txtprestamo_interes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprestamo_interesKeyPressed(evt);
            }
        });
        jPanel1.add(txtprestamo_interes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-dinero-30.png"))); // NOI18N
        jLabel12.setText("PRESTAMO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 30));

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1020, 700));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar1.setBackground(new java.awt.Color(102, 255, 102));
        agregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregar1MouseEntered(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("AGREGAR");

        javax.swing.GroupLayout agregar1Layout = new javax.swing.GroupLayout(agregar1);
        agregar1.setLayout(agregar1Layout);
        agregar1Layout.setHorizontalGroup(
            agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        agregar1Layout.setVerticalGroup(
            agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, 26));

        tabla_clientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Fecha", "Prestamo", "Cuotas", "Valor", "Mora", "Direccion", "Numero", "P.INTERES"
            }
        ));
        tabla_clientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_clientes1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_clientes1);
        if (tabla_clientes1.getColumnModel().getColumnCount() > 0) {
            tabla_clientes1.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabla_clientes1.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabla_clientes1.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabla_clientes1.getColumnModel().getColumn(4).setPreferredWidth(40);
            tabla_clientes1.getColumnModel().getColumn(5).setPreferredWidth(45);
            tabla_clientes1.getColumnModel().getColumn(6).setPreferredWidth(40);
            tabla_clientes1.getColumnModel().getColumn(7).setPreferredWidth(120);
            tabla_clientes1.getColumnModel().getColumn(9).setPreferredWidth(1);
        }

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 850, 430));

        eliminar1.setBackground(new java.awt.Color(255, 0, 0));
        eliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar1MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELIMINAR");

        javax.swing.GroupLayout eliminar1Layout = new javax.swing.GroupLayout(eliminar1);
        eliminar1.setLayout(eliminar1Layout);
        eliminar1Layout.setHorizontalGroup(
            eliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        eliminar1Layout.setVerticalGroup(
            eliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, 26));

        combo_categoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_categoria1ActionPerformed(evt);
            }
        });
        jPanel6.add(combo_categoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, -1));

        txtvalor_cuota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalor_cuota1ActionPerformed(evt);
            }
        });
        txtvalor_cuota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvalor_cuota1KeyPressed(evt);
            }
        });
        jPanel6.add(txtvalor_cuota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 70, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-nombre-30.png"))); // NOI18N
        jLabel18.setText("CELULAR");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        txtplazo_dias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplazo_dias1ActionPerformed(evt);
            }
        });
        txtplazo_dias1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtplazo_dias1KeyPressed(evt);
            }
        });
        jPanel6.add(txtplazo_dias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 120, -1));

        txtapellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellido1KeyPressed(evt);
            }
        });
        jPanel6.add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, -1));

        txtnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre1ActionPerformed(evt);
            }
        });
        txtnombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombre1KeyPressed(evt);
            }
        });
        jPanel6.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-ciudad-35.png"))); // NOI18N
        jLabel19.setText("DIRECCION");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 30));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-usuario-30.png"))); // NOI18N
        jLabel20.setText("NOMBRE");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 30));

        txtprestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprestamo1ActionPerformed(evt);
            }
        });
        txtprestamo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprestamo1KeyPressed(evt);
            }
        });
        jPanel6.add(txtprestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-dinero-30.png"))); // NOI18N
        jLabel21.setText("P.INTERES");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 30));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-tiempo-de-dinero-30.png"))); // NOI18N
        jLabel22.setText("PLAZO DIAS:");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CLIENTES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("CIUDAD:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 52, 30));

        editar1.setText("Editar");
        editar1.setBorder(null);
        editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar1ActionPerformed(evt);
            }
        });
        jPanel6.add(editar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 30));

        jButton5.setText("NoEditar");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("CLAVOS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 30));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-porcentaje-30.png"))); // NOI18N
        jLabel26.setText("Valor");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, -1));

        jPanel9.setBackground(new java.awt.Color(0, 204, 102));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("PAZ Y SALVO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));
        jPanel6.add(id_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 120, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 20, 30));

        txtdir1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdir1KeyPressed(evt);
            }
        });
        jPanel6.add(txtdir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, -1));

        jButton6.setText("Abono");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-nombre-30.png"))); // NOI18N
        jLabel29.setText("FECHA");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        txtcelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelular1ActionPerformed(evt);
            }
        });
        txtcelular1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcelular1KeyPressed(evt);
            }
        });
        jPanel6.add(txtcelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, -1));

        jButton7.setText("Reporte De Clientes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 150, 50));

        jButton8.setText("Reporte Este Cliente");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        txt1.setText("jTextField1");
        jPanel6.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 870, -1, -1));

        txt4.setText("jTextField1");
        jPanel6.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 880, -1, -1));

        txt5.setText("jTextField1");
        jPanel6.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 870, -1, -1));

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(t2);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1071, -1, 10));

        txtprestamo_interes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprestamo_interes1KeyPressed(evt);
            }
        });
        jPanel6.add(txtprestamo_interes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, -1));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-dinero-30.png"))); // NOI18N
        jLabel30.setText("PRESTAMO");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked

        this.eliminarCliente(id_eliminar);
        this.actualizarTabla(tabla_clientes, combo_categoria, tabla_clientes);

    }//GEN-LAST:event_eliminarMouseClicked

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        agregar(txtnombre, txtapellido, txtprestamo, txtplazo_dias, txtdir, txtvalor_cuota, txtcelular, txtprestamo_interes, tabla_clientes, combo_categoria);
    }//GEN-LAST:event_agregarMouseClicked

    private void combo_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_categoriaActionPerformed
        this.CargarClientes(combo_categoria, tabla_clientes);


    }//GEN-LAST:event_combo_categoriaActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        a = 1;
        editar.setBackground(Color.GREEN); // cambiar el color de fondo del botón
        jButton2.setBackground(UIManager.getColor("control")); // volver al color original del otro botón
    }//GEN-LAST:event_editarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        a = 0;

        jButton2.setBackground(Color.GREEN); // cambiar el color de fondo del botón
        editar.setBackground(UIManager.getColor("control")); // volver al color original del otro botón
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarMouseEntered

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        Clavos d1 = new Clavos();
        cambiarAotroPanel(d1);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        PazYSalvo P1 = new PazYSalvo();
    cambiarAotroPanel(P1);    }//GEN-LAST:event_jPanel5MouseClicked

    private void tabla_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clientesMouseClicked
        int filaSeleccionada = tabla_clientes.getSelectedRow();
        if (filaSeleccionada != -1) {

            String idClientes = tabla_clientes.getValueAt(filaSeleccionada, 0).toString();
            String nombre = tabla_clientes.getValueAt(filaSeleccionada, 1).toString();
            String apellido = tabla_clientes.getValueAt(filaSeleccionada, 2).toString();
            int prestamo = Integer.parseInt(tabla_clientes.getValueAt(filaSeleccionada, 3).toString());
            int plazo_dias = Integer.parseInt(tabla_clientes.getValueAt(filaSeleccionada, 9).toString());
            int valor_cuota = Integer.parseInt(tabla_clientes.getValueAt(filaSeleccionada, 5).toString());
            int prestamo_restante = Integer.parseInt(tabla_clientes.getValueAt(filaSeleccionada, 4).toString());

            String direccion = tabla_clientes.getValueAt(filaSeleccionada, 7).toString();
            String celular = tabla_clientes.getValueAt(filaSeleccionada, 8).toString();

            id_eliminar.setText(idClientes);
            txtnombre.setText(nombre);
            txtapellido.setText(apellido);
            txtprestamo.setText((Integer.toString(prestamo)));
            txtplazo_dias.setText((Integer.toString(plazo_dias)));
            txtvalor_cuota.setText((Integer.toString(valor_cuota)));
            txtdir.setText(direccion);
            txtcelular.setText(celular);
            txtprestamo_interes.setText(Integer.toString(prestamo_restante));
        }
    }//GEN-LAST:event_tabla_clientesMouseClicked

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed

    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed

        desplazarClientesConEnter(combo_categoria, txtnombre, txtapellido);
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            String text = txtapellido.getText();
            int caretPosition = txtapellido.getCaretPosition();
            if (caretPosition > 0 && text.charAt(caretPosition - 1) == '/') {
                // Eliminar el carácter "/" si se encuentra justo antes de la posición del cursor
                text = text.substring(0, caretPosition - 1) + text.substring(caretPosition);
                txtapellido.setText(text);
                txtapellido.setCaretPosition(caretPosition - 1);
            }
        } else {
            String text = txtapellido.getText();
            int numberCount = text.replaceAll("[^0-9]", "").length();
            if (numberCount > 0 && numberCount % 2 == 0 && numberCount <= 6) {
                text += "/";
                txtapellido.setText(text);
            }
            if (text.length() > 8) {
                text = text.substring(0, 8);
                txtapellido.setText(text);
            }
        }

        desplazarClientesConEnter(combo_categoria, txtapellido, txtcelular);
    }//GEN-LAST:event_txtapellidoKeyPressed

    private void txtdirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdirKeyPressed
        desplazarClientesConEnter(combo_categoria, txtdir, txtprestamo);

    }//GEN-LAST:event_txtdirKeyPressed

    private void txtprestamoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprestamoKeyPressed
        desplazarClientesConEnter(combo_categoria, txtprestamo, txtprestamo_interes);

    }//GEN-LAST:event_txtprestamoKeyPressed

    private void txtplazo_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplazo_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplazo_diasActionPerformed

    private void txtplazo_diasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplazo_diasKeyPressed
        desplazarClientesConEnter(combo_categoria, txtplazo_dias, txtvalor_cuota);

    }//GEN-LAST:event_txtplazo_diasKeyPressed

    private void txtcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelularActionPerformed


    }//GEN-LAST:event_txtcelularActionPerformed

    private void txtcelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyPressed
        desplazarClientesConEnter(combo_categoria, txtcelular, txtdir);

    }//GEN-LAST:event_txtcelularKeyPressed

    private void txtvalor_cuotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalor_cuotaKeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

            agregar(txtnombre, txtapellido, txtprestamo, txtplazo_dias, txtdir, txtvalor_cuota, txtcelular, txtprestamo_interes, tabla_clientes, combo_categoria);
            txtnombre.requestFocus();
        }
        desplazarClientesConEnter(combo_categoria, txtvalor_cuota, txtnombre);
    }//GEN-LAST:event_txtvalor_cuotaKeyPressed

    private void txtvalor_cuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalor_cuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalor_cuotaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Reportes_pdf pdf = new Reportes_pdf();
        try {
            pdf.reporteClientes();
        } catch (SQLException ex) {
            Logger.getLogger(Clientes_vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Paz.pasarHistorial(q, id_eliminar, txt, txt2, t1);
        int cliente = Integer.parseInt(id_eliminar.getText().trim());
        String clienteN = (txtnombre.getText().trim());

        Reportes_pdf pdf = new Reportes_pdf();
        pdf.generarInformePDF(cliente, clienteN);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtprestamo_interesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprestamo_interesKeyPressed
        desplazarClientesConEnter(combo_categoria, txtprestamo_interes, txtplazo_dias);
    }//GEN-LAST:event_txtprestamo_interesKeyPressed

    private void txtprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprestamoActionPerformed

    private void agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1MouseClicked

    private void agregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1MouseEntered

    private void tabla_clientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clientes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_clientes1MouseClicked

    private void eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseClicked

    private void combo_categoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_categoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_categoria1ActionPerformed

    private void txtvalor_cuota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalor_cuota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalor_cuota1ActionPerformed

    private void txtvalor_cuota1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalor_cuota1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalor_cuota1KeyPressed

    private void txtplazo_dias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplazo_dias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplazo_dias1ActionPerformed

    private void txtplazo_dias1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplazo_dias1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplazo_dias1KeyPressed

    private void txtapellido1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellido1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellido1KeyPressed

    private void txtnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1ActionPerformed

    private void txtnombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1KeyPressed

    private void txtprestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprestamo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprestamo1ActionPerformed

    private void txtprestamo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprestamo1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprestamo1KeyPressed

    private void editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void txtdir1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdir1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdir1KeyPressed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtcelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelular1ActionPerformed

    private void txtcelular1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelular1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelular1KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtprestamo_interes1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprestamo_interes1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprestamo_interes1KeyPressed

    private void tabla_clientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_clientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_clientesKeyPressed

    private void combo_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_categoriaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_categoriaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregar;
    private javax.swing.JPanel agregar1;
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_categoria1;
    private javax.swing.JButton editar;
    private javax.swing.JButton editar1;
    private javax.swing.JPanel eliminar;
    private javax.swing.JPanel eliminar1;
    private javax.swing.JTextField id_eliminar;
    private javax.swing.JTextField id_eliminar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel q;
    private javax.swing.JTable t1;
    private javax.swing.JTable t2;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JTable tabla_clientes1;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcelular1;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdir1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtplazo_dias;
    private javax.swing.JTextField txtplazo_dias1;
    private javax.swing.JTextField txtprestamo;
    private javax.swing.JTextField txtprestamo1;
    private javax.swing.JTextField txtprestamo_interes;
    private javax.swing.JTextField txtprestamo_interes1;
    private javax.swing.JTextField txtvalor_cuota;
    private javax.swing.JTextField txtvalor_cuota1;
    // End of variables declaration//GEN-END:variables
private int IdCategoria() {
        String sql = "select * from categoria where ciudad = '" + this.combo_categoria.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("idCategoria");;

            }
        } catch (SQLException e) {
            System.out.println("Error al obtener id categoria");
        }
        return obtenerIdCategoriaCombo;
    }

    public void Limpiar(JTextField txt, JTextField txt2, JTextField txt3, JTextField txt4, JTextField txt5, JTextField txt6, JTextField txt7, JTextField txt8) {
        txt.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        txt7.setText("");
        txt8.setText("");
    }

    public void CargarClientes(JComboBox ciudadbox, JTable tabla) {
        try {
            Connection conexion = Conexion.conectar();
            String ciudadSeleccionada = ciudadbox.getSelectedItem().toString();

            String consulta = "SELECT idClientes, nombre, apellido, prestamo, intereses, plazo_dias, mora, valor_cuota, direccion, numero_celular, prestamo_interes "
                    + "FROM clientes c "
                    + "INNER JOIN categoria ca ON c.idCategorias = ca.idcategoria "
                    + "WHERE ca.ciudad = ? "
                    + "ORDER BY c.orden ASC"; // Ordenar según la columna "orden" en la tabla "clientes"

            PreparedStatement ps = conexion.prepareStatement(consulta);
            ps.setString(1, ciudadSeleccionada);
            ResultSet rs = ps.executeQuery();

            // Limpiar la tabla antes de cargar los nuevos datos
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] fila = new Object[11];
                fila[0] = rs.getInt("idClientes");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getInt("prestamo");
                fila[4] = rs.getInt("prestamo_interes");
                fila[5] = rs.getInt("valor_cuota");
                fila[6] = rs.getInt("mora");
                fila[7] = rs.getInt("direccion");
                fila[8] = rs.getString("numero_celular");
                fila[9] = rs.getString("plazo_dias");
                fila[10] = rs.getString("prestamo_interes");
                model.addRow(fila);
            }

            rs.close();
            ps.close();
            conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void actualizarTabla(JTable clientes, JComboBox a, JTable b) {
        // Eliminar todos los registros de la tabla

        DefaultTableModel model = (DefaultTableModel) clientes.getModel();
        model.setRowCount(0);

        // Cargar los datos desde la base de datos en el modelo de tabla
        this.CargarClientes(a, b);

        // Actualizar la tabla
        clientes.setModel(model);
    }

    public void cargarCiudadbox(JComboBox ciudadBox) {

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement("SELECT ciudad FROM categoria");
            ResultSet rs = consulta.executeQuery();

            // Agregar los nombres y apellidos de los clientes en el JComboBox
            while (rs.next()) {
                String ciudad = rs.getString("Ciudad");

                ciudadBox.addItem(ciudad);

            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener la lista de clientes: " + e);
            JOptionPane.showMessageDialog(null, "Error al obtener la lista de ciudades.");
        }
    }

// Agregar un ActionListener al JComboBox para cargar los datos del cliente seleccionado
// Método para cargar los datos del cliente seleccionado en los campos de texto
    public void eliminarCliente(JTextField txt) {

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro Quieres Editar el cliente?", "Pregunta", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            int idCliente = Integer.parseInt(txt.getText());

            // Eliminar el registro del cliente en la tabla "clientes"
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement consulta = cn.prepareStatement("DELETE FROM clientes WHERE idClientes = ?");
                PreparedStatement consulta2 = cn.prepareStatement("DELETE FROM historial_abonos WHERE idClientes = ?");

                consulta.setInt(1, idCliente);
                consulta2.setInt(1, idCliente);
                consulta.executeUpdate();
                consulta2.executeUpdate();
                JOptionPane.showMessageDialog(null, "CLIENTE ELIMINADO", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                cn.close();
            } catch (SQLException ex) {
                System.err.println("Error al eliminar el cliente: " + ex);
                JOptionPane.showMessageDialog(null, "Error al eliminar el cliente.");
            }

            // Código para cuando el usuario selecciona Sí.
        } else if (respuesta == JOptionPane.NO_OPTION) {

            // Código para cuando el usuario selecciona No.
        } else if (respuesta == JOptionPane.CLOSED_OPTION) {
            System.out.println("El usuario ha cerrado el diálogo.");
            // Código para cuando el usuario cierra el diálogo sin seleccionar una opción.
        }

    }

    public void comprobar() {

        LocalDate fechaActual = LocalDate.now();
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement("SELECT * FROM clientes WHERE estado NOT IN (1, 3) AND fecha_vencimiento < ?");

            consulta.setDate(1, java.sql.Date.valueOf(fechaActual));
            ResultSet rs = consulta.executeQuery();
            while (rs.next()) {
                int idCliente = rs.getInt("idclientes");
                LocalDate fechaVencimiento = rs.getDate("fecha_vencimiento").toLocalDate();
                long diferenciaEnDias = ChronoUnit.DAYS.between(fechaVencimiento, fechaActual);
                int mora = diferenciaEnDias > 0 ? (int) diferenciaEnDias : 0;

                PreparedStatement consultaUpdate = cn.prepareStatement("UPDATE clientes SET estado = 2, mora = ? WHERE idclientes = ?");
                consultaUpdate.setInt(1, mora);

                consultaUpdate.setInt(2, idCliente);
                consultaUpdate.executeUpdate();

            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al comprobar la fecha de vencimiento: " + e);
        }

    }

    private void cambiarAotroPanel(JPanel nuevoPanel) {
        // Obtener la referencia al JFrame principal
        Menu frame = (Menu) SwingUtilities.getWindowAncestor(this);
        // Llamar al método cambiarContenido() del JFrame principal
        frame.cambiarContenido(nuevoPanel);
    }

    public void editarCliente() {
        
        
        
             int respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro Quieres Editar el cliente?", "Pregunta", JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
          try {
            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement(
                    "UPDATE clientes SET nombre = ?, apellido = ?, prestamo = ?, plazo_dias = ?, valor_cuota = ?, direccion = ?, numero_celular = ?, prestamo_interes = ? WHERE idclientes = ?"
            );

            String texto = txtapellido.getText();
            if (texto.isEmpty()) {
                LocalDate fechaHoy = LocalDate.now();
                DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String fecha = fechaHoy.format(formateador);
                consulta.setString(2, fecha);
            } else {
                consulta.setString(2, txtapellido.getText());

            }
            consulta.setString(1, txtnombre.getText());
            consulta.setInt(3, Integer.parseInt(txtprestamo.getText()));
            consulta.setInt(4, Integer.parseInt(txtplazo_dias.getText()));
            consulta.setDouble(5, Integer.parseInt(txtvalor_cuota.getText()));
            consulta.setString(6, txtdir.getText());
            consulta.setString(7, txtcelular.getText());
            consulta.setInt(8, Integer.parseInt(txtprestamo_interes.getText()));
            consulta.setInt(9, Integer.parseInt(id_eliminar.getText()));

            int rowsUpdated = consulta.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Cliente actualizado exitosamente.");
   JOptionPane.showMessageDialog(null, "CLIENTE EDITADO", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } else {
                System.out.println("No se encontró el cliente con el ID especificado.");
            }
        } catch (SQLException e) {
            System.err.println("Error al editar el cliente: " + e.getMessage());
        }

                 
            
            // Código para cuando el usuario selecciona Sí.
        } else if (respuesta == JOptionPane.NO_OPTION) {
          
            // Código para cuando el usuario selecciona No.
        } else if (respuesta == JOptionPane.CLOSED_OPTION) {
            System.out.println("El usuario ha cerrado el diálogo.");
            // Código para cuando el usuario cierra el diálogo sin seleccionar una opción.
        }
     
        
      
    }

    public void agregar(JTextField txt, JTextField txt2, JTextField txt3, JTextField txt4, JTextField txt5, JTextField txt6, JTextField txt7, JTextField txt8, JTable clientes, JComboBox b) {
        if (a == 1) {
            editarCliente();
            this.actualizarTabla(clientes, b, clientes);
        } else {
            Clientes cliente = new Clientes();
            Ctrl_Clientes controlCliente = new Ctrl_Clientes();

            String categoria = "";
            categoria = b.getSelectedItem().toString().trim();
            if (txt.getText().equals("") || txt3.getText().equals("") || txt4.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
                txt.setBackground(Color.red);
                txt2.setBackground(Color.red);
                txt3.setBackground(Color.red);
                txt4.setBackground(Color.red);
                txt5.setBackground(Color.red);
                txt6.setBackground(Color.red);
                txt7.setBackground(Color.red);
            } else {
                try {
                    String texto = txt2.getText();
                    if (texto.isEmpty()) {
                        LocalDate fechaHoy = LocalDate.now();
                        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                        String fecha = fechaHoy.format(formateador);
                        cliente.setApellido(fecha);
                    } else {
                        cliente.setApellido(txt2.getText().trim());
                    }
                    cliente.setNombre(txt.getText().trim());
                    cliente.setPrestamo(Integer.parseInt(txt3.getText().trim()));
                    cliente.setPrestamo_intereses(Integer.parseInt(txt8.getText().trim()));
                    cliente.setPrestamo_restante(Integer.parseInt(txt8.getText().trim()));
                    cliente.setDireccion((txt5.getText().trim()));
                    cliente.setPrestamo_intereses(Integer.parseInt(txt8.getText().trim()));
                    cliente.setValor_cuota(Integer.parseInt(txt6.getText().trim()));
                    cliente.setNumero_celular((txt7.getText().trim()));
                    cliente.setPlazo_dias(Integer.parseInt(txt4.getText().trim()));
                    cliente.setMora(0);
                    double txtValue = Double.parseDouble(txt3.getText().trim());
                    double txt8Value = Double.parseDouble(txt8.getText().trim());
                    double txt4Value = Double.parseDouble(txt4.getText().trim());

                    double intereses = (txt8Value - txtValue);
                    double nintereses = (intereses / txtValue);
                    intereses = (nintereses * 100);
                    cliente.setIntereses(intereses);
                    System.out.println("Intereses: " + intereses);
                    LocalDate fechaActual = LocalDate.now();
                    LocalDate fechaVencimiento = fechaActual.plusDays(Integer.parseInt(txt4.getText().trim()));
                    Date fechaVencimientoSql = java.sql.Date.valueOf(fechaVencimiento);
                    cliente.setFecha_vencimiento(fechaVencimientoSql);
                    this.IdCategoria();
                    cliente.setIdCategoria(obtenerIdCategoriaCombo);

                    if (controlCliente.guardar(cliente)) {
                        JOptionPane.showMessageDialog(null, "Registro Guardado");
                        txt.setBackground(Color.green);
                        txt2.setBackground(Color.green);
                        txt3.setBackground(Color.green);
                        txt4.setBackground(Color.green);
                        txt7.setBackground(Color.green);
                        txt5.setBackground(Color.green);
                        txt6.setBackground(Color.green);
                        this.Limpiar(txt, txt2, txt3, txt4, txt5, txt6, txt7, txt8);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Guardar");
                    }
                } catch (HeadlessException | NumberFormatException e) {
                    System.out.println("Error en: " + e);
                }
                DefaultTableModel model = (DefaultTableModel) clientes.getModel();
                Object[] fila = new Object[10];
                fila[0] = cliente.getIdClientes();
                fila[1] = cliente.getNombre();
                fila[2] = cliente.getApellido();
                fila[3] = cliente.getPrestamo();
                fila[9] = cliente.getPlazo_dias();
                fila[5] = cliente.getValor_cuota();
                fila[6] = cliente.getMora();
                fila[7] = cliente.getDireccion();
                fila[8] = cliente.getNumero_celular();
                fila[4] = cliente.getPrestamo_intereses();
                model.addRow(fila);

            }

            // Agregar el nuevo cliente al final de la tabla
            this.actualizarTabla(clientes, b, clientes);
        }
    }

    public void desplazarClientesConEnter(JComboBox<String> clientes_combo, JTextField abono, JTextField desT) {
        abono.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {

                int keyCode = e.getKeyCode();
                if (e.getKeyCode() == KeyEvent.VK_ENTER && e.isControlDown()) {

                    int selectedIndex = clientes_combo.getSelectedIndex();
                    int itemCount = clientes_combo.getItemCount();
                    if (selectedIndex >= 0 && selectedIndex < itemCount - 1) {
                        clientes_combo.setSelectedIndex(selectedIndex + 1);
                    } else if (selectedIndex == itemCount - 1) {
                        clientes_combo.setSelectedIndex(0);
                    }

                } else if (keyCode == KeyEvent.VK_ENTER) {
                    desT.requestFocus();
                }
            }
        });

    }

    private void restringirSoloNumeros(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                String text = fb.getDocument().getText(0, fb.getDocument().getLength()) + string;
                if (!text.matches("[\\d/]*")) {  // Filtra solo números y "/"
                    return;
                }
                super.insertString(fb, offset, string, attr);
            }

            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
                String newText = currentText.substring(0, offset) + text + currentText.substring(offset + length);
                if (!newText.matches("[\\d/]*")) {  // Filtra solo números y "/"
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
            }
        });
    }
}
